version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: nest-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: anhthang123
      POSTGRES_USER: postgres
      POSTGRES_DB: ecomerce-nest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest

networks:
  nest:
    driver: bridge

volumes:
  postgres_data:
